MathJax.Hub.Config({
   "TeX" : {
       Macros: {
           dimension: "\\operatorname{dim}",
           diag: "\\operatorname{diag}",
           argmin: "\\operatorname{arg\\,min}",
           argmax: "\\operatorname{arg\\,max}",
           chol: "\\operatorname{chol}",
           gvn: "\\operatorname{|}",
           trace: "\\operatorname{Trace}",
           vct: ["\\boldsymbol{#1}", 1],
           mtx: ["\\mathbf{#1}", 1],
           set: ["\\mathcal{#1}", 1],
           fset: ["\\lbr #1 \\rbr", 1],
           reals: "\\mathbb{R}",
           naturals: "\\mathbb{N}",
           ind: ["\\mathbb{1}\\lsb #1 \\rsb", 1],
           bigo: ["\\mathcal{O}\\lpa #1\\rpa", 1],
           lpa: "\\left(",
           rpa: "\\right)",
           lbr: "\\left\\lbrace",
           rbr: "\\right\\rbrace",
           lsb: "\\left[",
           rsb: "\\right]",
           prob: ["\\mathbb{P}\\lsb #1 \\rsb", 1],
           pden: ["\\mathbb{p}_{\\scriptscriptstyle #1}\\lsb #2 \\rsb", 2],
           tgtden: ["\\mathbbm{\\pi}_{\\scriptscriptstyle #1}\\lsb #2 \\rsb", 2],
           rvar: ["\\mathsf{#1}", 1],
           rvct: ["\\bm{\\rvar{#1}}", 1],
           nrm: ["\\mathcal{N}\\lpa #1 \\rpa", 1],
           rng: ["\\lbr #1 \\dots #2 \\rbr", 2],
           expc: ["\\mathbb{E}_{#1}\\lsb #2 \\rsb", 2],
           var: ["\\mathbb{V}\\lsb #1 \\rsb", 1],
           dr: "\\mathrm{d}",
           td: ["\\frac{\\dr #1}{\\dr #2}", 2],
           pd: ["\\frac{\\partial #1}{\\partial #2}", 2],
           pdd: ["\\frac{\\partial^2 #1}{\\partial #2 \\partial #3}", 3],
           tr: "^\\mathrm{T}",
           sml: ["#1", 1],
           obs: ["\\breve{#1}", 1],
           lebm: ["\\lambda^{#1}\\lbr \\dr #2 \\rbr", 2],
           haum: ["\\mathcal{H}^{#1}\\lbr \\dr #2 \\rbr", 2],
           dirm: ["\\delta^{#1}_{#2}\\lbr \\dr #3 \\rbr", 3]
       }
   }
});
